#ifndef CONFIG_FIRMWARE_H_
#define CONFIG_FIRMWARE_H_

#include <motor_control_manager.h>

#define COMMUNICATION_CYCLE_TIME		MOTOR_CONTROL_CYCLE_TIME_10000
#define STATE_MACHINE_CYCLE_TIME		MOTOR_CONTROL_CYCLE_TIME_250
#define VELOCITY_MEASURE_CYCYLE_TIME	MOTOR_CONTROL_CYCLE_TIME_250
#define VELOCITY_CONTROL_CYCLE_TIME		MOTOR_CONTROL_CYCLE_TIME_250
#define CURRENT_TRANS_CYCYLE_TIME		MOTOR_CONTROL_CYCLE_TIME_125
#define CURRENT_CONTROL_CYCLE_TIME 		MOTOR_CONTROL_CYCLE_TIME_125
#define REVUP_CONTROLLER_CYCLE_TIME		MOTOR_CONTROL_CYCLE_TIME_62_50
#define OBSERVER_CYCLE_TIME				MOTOR_CONTROL_CYCLE_TIME_62_50
#define MODULATION_CYCLE_TIME 			MOTOR_CONTROL_CYCLE_TIME_62_50



#endif /* CONFIG_FIRMWARE_H_ */
