#ifndef CONFIG_MOTOR_H
#define CONFIG_MOTOR_H

#define MOTOR_NOM_VOLTAGE_MV		15000.0f
#define MOTOR_RESISTANCE_MOHM		2100.0f
#define MOTOR_INDUCTANE_MHENRY		1.0f
#define MOTOR_POLE_PAIRS 			2u
#define MOTOR_OMEGA_MAX   			1200.0f

#define MOTOR_ALIGNMENT_VQ_MV			750.0f
#define MOTOR_OPEN_LOOP_VQ_MV			1200.0f
#define	MOTOR_ALIGNMENT_TIME_MS			50u
#define	MOTOR_ALIGMENT_TIME_TICKS		((float)MOTOR_ALIGNMENT_TIME_MS / ((1.0f / PWM_FREQ_HZ) * 1000.0f))
#define MOTOR_STABILIZATION_TIME_MS		50u
#define	MOTOR_STABILIZATION_TIME_TICKS	((float)MOTOR_STABILIZATION_TIME_MS / ((1.0f / PWM_FREQ_HZ) * 1000.0f))

#define MOTOR_OPEN_LOOP_TARGET_ELEC_FREQ_HZ 	10.0f
#define MOTOR_OPEN_LOOP_ACCELERATION_HZ_PER_S 	15.0f

#define MOTOR_OPEN_LOOP_TARGET_ELEC_SPEED_RAD_S (MOTOR_OPEN_LOOP_TARGET_ELEC_FREQ_HZ * CONSTANT_TWO_PI)
#define MOTOR_OPEN_LOOP_ACCELERATION_RAD_S2		(MOTOR_OPEN_LOOP_ACCELERATION_HZ_PER_S * CONSTANT_TWO_PI)



#endif /* CONFIG_MOTOR_H */
