#ifndef MOTOR_H_
#define MOTOR_H_

#define MOTOR_NOM_VOLTAGE_MV			16000.0f
#define MOTOR_MAX_CURRENT_MA			2000.0f
#define MOTOR_RESISTANCE_MOHM			275.0f
#define MOTOR_INDUCTANCE_MHENRY			0.135f
#define MOTOR_MAX_RPM					4000
#define MOTOR_POLE_PAIRS 				7u
#define MOTOR_KV_VALUE					360

#endif /* MOTOR_H_ */
